Ruby on Rails/MiBlog/config/routes.rb
Rails.application.routes.draw do
  resources :pregunta

end

Ruby on Rails/MiBlog/app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
end

Ruby on Rails/MiBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby on Rails/MiBlog/app/controllers/pregunta_controller.rb
class PreguntaController < ApplicationController
  before_action :set_preguntum, only: [:show, :edit, :update, :destroy]

  # GET /pregunta
  # GET /pregunta.json
  def index
    @pregunta = Preguntum.all
  end

  # GET /pregunta/1
  # GET /pregunta/1.json
  def show
  end

  # GET /pregunta/new
  def new
    @preguntum = Preguntum.new
  end

  # GET /pregunta/1/edit
  def edit
  end

  # POST /pregunta
  # POST /pregunta.json
  def create
    @preguntum = Preguntum.new(preguntum_params)

    respond_to do |format|
      if @preguntum.save
        format.html { redirect_to @preguntum, notice: 'La pregunta ya está posteada' }
        format.json { render :show, status: :created, location: @preguntum }
      else
        format.html { render :new }
        format.json { render json: @preguntum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pregunta/1
  # PATCH/PUT /pregunta/1.json
  def update
    respond_to do |format|
      if @preguntum.update(preguntum_params)
        format.html { redirect_to @preguntum, notice: 'La pregunta fue actualizada' }
        format.json { render :show, status: :ok, location: @preguntum }
      else
        format.html { render :edit }
        format.json { render json: @preguntum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pregunta/1
  # DELETE /pregunta/1.json
  def destroy
    @preguntum.destroy
    respond_to do |format|
      format.html { redirect_to pregunta_url, notice: 'La pregunta fue eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preguntum
      @preguntum = Preguntum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preguntum_params
      params.require(:preguntum).permit(:titulo, :post, :etiqueta)
    end
end

Ruby on Rails/MiBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby on Rails/MiBlog/app/helpers/pregunta_helper.rb
module PreguntaHelper
end

Ruby on Rails/MiBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby on Rails/MiBlog/app/views/pregunta/_form.html.erb
<%= form_for(@preguntum) do |f| %>
  <% if @preguntum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preguntum.errors.count, "error") %> prohibited this preguntum from being saved:</h2>

      <ul>
      <% @preguntum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :etiqueta %><br>
    <%= f.text_field :etiqueta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby on Rails/MiBlog/app/views/pregunta/edit.html.erb
<h1>Editing preguntum</h1>

<%= render 'form' %>

<%= link_to 'Show', @preguntum %> |
<%= link_to 'Back', pregunta_path %>

Ruby on Rails/MiBlog/app/views/pregunta/index.html.erb
<h1>Listing pregunta</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Post</th>
      <th>Etiqueta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pregunta.each do |preguntum| %>
      <tr>
        <td><%= preguntum.titulo %></td>
        <td><%= preguntum.post %></td>
        <td><%= preguntum.etiqueta %></td>
        <td><%= link_to 'Show', preguntum %></td>
        <td><%= link_to 'Edit', edit_preguntum_path(preguntum) %></td>
        <td><%= link_to 'Destroy', preguntum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preguntum', new_preguntum_path %>

Ruby on Rails/MiBlog/app/views/pregunta/new.html.erb
<h1>New preguntum</h1>

<%= render 'form' %>

<%= link_to 'Back', pregunta_path %>

Ruby on Rails/MiBlog/app/views/pregunta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @preguntum.titulo %>
</p>

<p>
  <strong>Post:</strong>
  <%= @preguntum.post %>
</p>

<p>
  <strong>Etiqueta:</strong>
  <%= @preguntum.etiqueta %>
</p>

<%= link_to 'Edit', edit_preguntum_path(@preguntum) %> |
<%= link_to 'Back', pregunta_path %>